### ISSUE TITLE
mod_cluster crashes apache thread if multiple nodes report the same AJP connect string

### ISSUE THREAD

**Issue by ToeBee** [modcluster/mod_cluster#138]
We ran into what was ultimately a configuration error in our chef setup but because of how mod_cluster failed, it took us a while to figure out what the problem really was. It presented as random crashes in apache processes with the following two lines in error.log:

    [notice] child pid 12758 exit signal Aborted (6), possible coredump in /etc/apache2
    apache2: misc/apr_reslist.c:159: reslist_cleanup: Assertion `rl->ntotal == 0' failed.

The ultimate problem was that our wildfly instances were being set up to bind to 0.0.0.0 and then were reporting that IP to mod_cluster. Detail that may be relevant here: We are not using multicast for discovery. We are explicitly setting the IP of the apache servers in the wildfly config like so:

    <subsystem xmlns="urn:jboss:domain:modcluster:1.2">
        <mod-cluster-config advertise-socket="modcluster" proxy-list="10.133.248.4:6666,10.133.248.5:6666,10.133.248.6:6666,10.133.248.7:6666" advertise="false" load-balancing-group="${mycluster.modcluster.lbgroup:StdLBGroup}" connector="ajp">
            <dynamic-load-provider>
                <load-metric type="busyness"/>
            </dynamic-load-provider>
        </mod-cluster-config>
    </subsystem>

Anyway, the end result is that the mod_cluster-manager page was displaying this (node details removed for brevity):
![mod_cluster_manager](https://cloud.githubusercontent.com/assets/348948/5965942/bb9946de-a7c5-11e4-956b-dc671ecebea8.png)

Now, clearly this configuration is wrong. The only reason it even worked in the first place to serve up **any** content was that wildfly is currently running on the same host as apache so sending requests to 0.0.0.0 actually works. If this was not the case, requests would have thrown 404s or 503s or something and the problem would have been obvious. But the setup worked well enough that we thought maybe it was some kind of mismatch between apache and mod_cluster since we were using an older version of mod_cluster initially. So we spent time trying to chase down possible bugs or issues in our installation process.

Our current theory is that the crashes happened when mod_cluster decided to switch a user to a different node for load balancing reasons and then either the duplicated connect string or the fact that when it tried to talk to a different node, it got the same one on 0.0.0.0 caused the crash.

I'm not sure what would constitute a fix for this. One simple solution might just be to have mod_cluster complain loudly if two nodes register themselves with the same connect string. Is there any valid reason for this to ever happen? One line in error.log would have saved us hours of debugging.

**Comment by Karm** [comment]
Dear Toby, thank you for the report. I opened [MODCLUSTER-448](https://issues.jboss.org/browse/MODCLUSTER-448) so as we could track the feature request in Jira where we have our dev & qa process in place. Stay tuned...

**Comment by jfclere** [comment]
https://issues.jboss.org/browse/MODCLUSTER-91 ?

**Comment by rhusar** [comment]
Continue tracking on https://issues.jboss.org/browse/MODCLUSTER-448, closing here.
