### ISSUE TITLE
mod_cluster_slotmem.so failed to load into httpd 2.4.6-19 and 2.4.6-30

### ISSUE THREAD

**Issue by sebbalex** [modcluster/mod_cluster#141]
I tried to download every release available here even the 1.3.1 Beta2 unsuccessfully.
I tried to compile them manually or just downloading the binary "so" but everytime my httpd failed to start with this error message:

Can't locate API module structure `slotmem_module' in file /etc/httpd/modules/mod_cluster_slotmem.so: /etc/httpd/modules/mod_cluster_slotmem.so: undefined symbol: slotmem_module

others modules load correctly except for this one!
Is there a solution/workaround
Thanks a lot.

**Comment by Karm** [comment]
Did you load it properly in the config?

    LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so

It is called ``` cluster_slotmem_module```, not ```slotmem_module```.

Cheers 
K.

**Comment by rhusar** [comment]
We had to rename the module but the documentation is still stale... I ll asing to myself.

**Comment by Karm** [comment]
Closing. Updated documentation with regard to ```cluster_slotmem_module``` is available on [http://modcluster.io](http://modcluster.io/documentation/#configure-httpd).

**Comment by Karm** [comment]
Meh, don't have the right to actually close this issue :confused: Anyway, feel free to do so @rhusar
