### ISSUE TITLE
Links at http://mod-cluster.jboss.org/ are broken

### ISSUE THREAD

**Issue by henriqueqc** [modcluster/mod_cluster#144]
Various links at http://mod-cluster.jboss.org/ are broken, they are prepending an extra "/mod_cluster/" to the correct addresses.

For example, the "Documentation" link currently points to: http://mod-cluster.jboss.org/mod_cluster/docs which is broken, but the correct address is: http://mod-cluster.jboss.org/docs

**Comment by Karm** [comment]
THX for spotting it. We will reach out to the site admins.
