### ISSUE TITLE
mod_cluster_slotmem.so failed to load into httpd v2.2.22

### ISSUE THREAD

**Issue by RenQilei** [modcluster/mod_cluster#204]
I tried to upgrade mod_cluster from v1.2.x to v1.3.1.final on **Apache v2.2.22**, which is satisfied with the lowest requirements.

Unfortunately, when I restart the apache, I got the error message like:
`/opt/app/apache2/modules/mod_cluster/mod_cluster_slotmem.so: undefined symbol: ap_unixd_config`

I have searched around for this issue, but no available answers found.

Please kindly refer me to correct solutions. Thanks.

**Comment by Karm** [comment]
Dear @RenQilei, it is [this thread on our discussion forum](https://developer.jboss.org/thread/236809). If you scroll down, there are explanations.

TL;DR version: You cannot just take mod_cluster 1.3.x binaries that were compiled with httpd 2.4.x and load them into httpd 2.2.x, you have to recompile them.

There is a tutorial on compiling your mod_cluster sources on Linux: [mod_cluster with CMAKE](http://modcluster.io/examples/#apache-http-server-examples).

Let us know if it helped you.

Cheers
-K-

**Comment by RenQilei** [comment]
Dear Karm,

Thanks for your advice. I have successfully built mod_cluster from its sources with mod_proxy_cluster.

However, when I used CMAKE, I had got error message "Could not find APR library" until I commented two lines in CMakeLists.txt:

```
FIND_PACKAGE(APR REQUIRED)
FIND_PACKAGE(APACHE REQUIRED)
```

and used command with attributes to specify path of apr/aprutil/apache instead.

My apache version is v2.2.22 as I mentioned above, in which apr/aprutil have included in apache ```include``` folder already. Is there any tricky in it I did not use correctly or there are some vulnerable in this file actually?

Thanks for your help whatever.

Regards,
Ren

**Comment by Karm** [comment]
Hi @RenQilei, 
these CMAKE modules actively look up necessary dependencies on your system. If they fail for some reason or if you would like to provide particular versions from non-standard locations, you could easily do so via command line directives.

In my case, I have httpd and apr installed on my workstation, but these are generally not what I want to compile with. I need to point to various different devel versions of httpd and APR, so I compile mod_cluster with explicit paths set:

```
cmake ../ -DAPRUTIL_INCLUDE_DIR=/home/karm/Projects/MOD_CLUSTER/httpd-2.4.20/srclib/apr-util/include -DAPRUTIL_LIBRARY=/home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/lib/libaprutil-1.so -DAPR_INCLUDE_DIR=/home/karm/Projects/MOD_CLUSTER/httpd-2.4.20/srclib/apr/include -DAPR_LIBRARY=/home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/lib/libapr-1.so -DAPACHE_INCLUDE_DIR=/home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/include
-- Found APR: /home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/lib/libapr-1.so
-- Found APRUTIL: /home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/lib/libaprutil-1.so
-- Found APACHE: /home/karm/Projects/MOD_CLUSTER/httpd-2.4.20-build/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/karm/Projects/MOD_CLUSTER/mod_proxy_cluster/native/build
```

If you know how to enhance mod_cluster CMAKE declarations, please comment or submit a pull request :octocat:
