### ISSUE TITLE
Native Sources Missing in Master Branch

### ISSUE THREAD

**Issue by joecarder** [modcluster/mod_cluster#216]
Documentation @ http://docs.jboss.org/mod_cluster/1.3.0/html/native.building.html#d0e770 says to build from git master branch.  Master branch does not contain the native source directories to build from as described in documentation.   I was able to find the native sources directory in the 1.3.x branch and build from there.  Not sure if the repo is functioning as expected and the documentation needs to be updated, or vice versa. Please update either one as required, thank you!

**Comment by Karm** [comment]
Hi @joecarder, documentation updated, see: http://modcluster.io/documentation/#building-httpd-modules
