### ISSUE TITLE
Handling for unavailable nodes

### ISSUE THREAD

**Issue by leichtundkross** [modcluster/mod_cluster#244]
We use Wildfly 10 with modcluster to balance a couple of app server instances. Now, we are looking for a way to tell the load balancer that a node is in trouble and should be removed from the list of balancing members.

I did not find a (documented) way to this in an elegant manner. So, I added a custom LoadMetric that reports errors by throwing an exception (at least this is what the API invites to). However, my exception is swallowed in DynamicLoadBalanceFactorProvider#getLoadBalanceFactor().

The point is: Is there a possibility to invoke a kind of DISABLE-APP event or something similar? If not, a nicer exception handling in DynamicLoadBalanceFactorProvider would be desirable. For example, returning -1 in case of an exception will lead to disablement of the cluster member.

**Comment by rhusar** [comment]
Hey Andreas,

That's a fair point. I think we should support this. Ideally, this will be done with a specific exception the load metric will throw.

Sorry, I didn't seem to get notification about the issue. We use Jira to track issues primarily, but I keep this option on GitHub for user convenience. I have opened your issue as https://issues.jboss.org/browse/MODCLUSTER-574 please follow the progress there.

Rado
