### ISSUE TITLE
2.0.0.Alpha1 version is maintained on master branch

### ISSUE THREAD

**Issue by daghost97** [modcluster/mod_cluster#254]
I noticed that support for tomcat 8.5 was only added on the master branch.  Are the features included on master stable?  If so, I was curious if a separate branch and tag could be created for the 2.0.0.Alpha1 version, similar to how the previous 1.3.x was maintained.  I would like to leverage this product but wanted a way to ensure my build was reproducible.

**Comment by rhusar** [comment]
Hello Shaun, you are right. The 8.5 support was added via this Jira https://issues.jboss.org/browse/MODCLUSTER-493 and the corresponding integration code resides in https://github.com/modcluster/mod_cluster/tree/master/container/tomcat85 which supports both tomcat9 and tomcat85 (tomcat85 itself was branched from tomcat9 development branch at some point, thus the same integration code).

Would it be helpful to you if we cut a 2.0.0.Alpha1 release?

**Comment by daghost97** [comment]
Yes, that would be very helpful in tracking this release to final.

**Comment by rhusar** [comment]
@daghost97 Slight change here, we now have 1.4.x branch with first Alpha1 release which contains Tomcat 8.5 support: https://github.com/modcluster/mod_cluster/tree/1.4.0.Alpha1
