### ISSUE TITLE
issue related to starting apache after configuring for mod_cluster

### ISSUE THREAD

**Issue by ShivaramVenkat** [modcluster/mod_cluster#272]
I am configuring  mod_cluster, using  apache, Jboss EAP 6.3. Extracted mod_cluster-1.2.6.Final-linux2-x64-so.tar and copied :mod_advertise.so, mod_manager.so, mod_slotmem.so, mod_proxy_cluster.so into /etc/httpd/modules directory.
Made following changed to httpd.conf file:
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
#LoadModule slotmem_module modules/mod_slotmem.so
LoadModule manager_module modules/mod_manager.so
#LoadModule proxy_cluster_module modules/mod_proxy_cluster.so

<IfModule manager_module>
ManagerBalancerName mycluster

Listen 127.0.0.1:1001
<VirtualHost 127.0.0.1:1001>
  <Directory />
     Order deny,allow
     Allow from all
  </Directory>
    KeepAliveTimeout 300
    MaxKeepAliveRequests 0
    #AdvertiseFrequency 5
    #ServerAdvertise off
EnableMCPMReceive On

 <Location /mod_cluster-manager>
   SetHandler mod_cluster-manager
   Order deny,allow
   Allow from all
    Require all granted
  </Location>
</VirtualHost>
</IfModule>

While running the apache server,  I am getting following error. Apache server is not coming up:
 httpd: Syntax error on line 357 of /etc/httpd/conf/httpd.conf: Cannot load modules/mod_manager.so into server: /etc/httpd/modules/mod_manager.so: undefined symbol: ap_my_generation
What is the solution to fix above issu

**Comment by Karm** [comment]
@ShivaramVenkat Your setup cannot work.  You are mixing 3 incompatible things together:
 - httpd 2.2.x configuration directives
 - httpd 2.4.x configuration directives
 - obsolete version of mod_cluster that is full of CVEs and performance issues and *that is not compatible with httpd 2.4.x*  (ap_my_generation no longer accessible in 2.4.x API)

**Solution:**
 * use Apache HTTP Server 2.4.x+ (e.g. 2.4.23)
 * compile [latest 1.3.x branch](https://github.com/modcluster/mod_cluster/tree/1.3.x) of mod_cluster or the latest [master of mod_proxy_cluster](https://github.com/modcluster/mod_proxy_cluster) with it
 * on Linux, it is [fairly easy](http://modcluster.io/documentation/#building-httpd-modules) to compile with your httpd

**Java side:**
Don't worry about having mod_proxy_cluster modules of version 1.3.x on the Apache HTTP Server side and mod_cluster 1.2.x subsystem in EAP 6. The protocol they talk to each other is compatible.

**Comment by Karm** [comment]
@ShivaramVenkat If you have any troubles compiling yourself, post a comment and we will help you. Regular Linux releases are coming in a couple of days on https://ci.modcluster.io/. The CI does just Windows right now.
