### ISSUE TITLE
ERROR MODCLUSTER000042

### ISSUE THREAD

**Issue by zgq1987** [modcluster/mod_cluster#355]
ERROR [org.jboss.modcluster] (ContainerBackgroundProcessor[StandardEngine[jboss.web]]) MODCLUSTER000042: Error null sending INFO command to X.X.X.X/X.X.X.X:6666, configuration will be reset: null
This error is why? many thanks!

**Comment by Karm** [comment]
Hello @zgq1987,

Your worker is unable to contact your balancer. Mind you the communication is bidirectional with mod_cluster. Worker must be able to establish a new connection to the balancer. Your network setup might be the problem. Check the NIC worker thinks the balancer is available on.
