### ISSUE TITLE
Docs link to Advertize.java is broken

### ISSUE THREAD

**Issue by dcfsc** [modcluster/mod_cluster#421]
On the docs page https://docs.modcluster.io/#_it_is_not_working_what_should_i_do

```
Check that Advertise message are received on the cluster node. A small
 Java utility could be used to check Advertise. It is in the 
mod_cluster repository and can be compiled using javac. The 
output should be something like:
```
The text `small Java utility` links to https://github.com/modcluster/mod_cluster/blob/master/test/java/Advertize.java which is 404.

1. Did Advertize.java move? I cannot find it.
2. Was it replaced by a new test fixture?

The doc needs to be updated to reflect these changes.

**Comment by Karm** [comment]
@dcfsc   This is the utility:

https://github.com/modcluster/mod_proxy_cluster/blob/master/test/java/Advertize.java

**Comment by rhusar** [comment]
I can fix the docs on Monday unless a PR is open by then.

**Comment by dcfsc** [comment]
@rhusar Added PR. Thanks for locating issue.

**Comment by rhusar** [comment]
merged.
