### ISSUE TITLE
mod_proxy_cluster.c:225:5: warning: implicit declaration of function 'ap_proxy_port_of_scheme' [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by paramesh1987** [modcluster/mod_cluster#463]
Hi,

Am facing below warning while compiling mod_proxy_cluster module for apache httpd, with the below warning the mod_proxy_cluster module (mod_proxy_cluster.so) was generated.
the remaining modules advertise, mod_cluster_slotmem and mod_manager able to compile with out any error or warning.

[root@localhost mod_proxy_cluster]# make
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99  -pthread      -DLINUX -D_REENTRANT -D_GNU_SOURCE     -I/opt/apache2/include -I. -I/usr/include/apr-1 -I../include -prefer-pic -c mod_proxy_cluster.c && touch mod_proxy_cluster.slo
**mod_proxy_cluster.c: In function 'create_worker':
mod_proxy_cluster.c:291:5: **warning:** implicit declaration of function 'ap_proxy_port_of_scheme' [-Wimplicit-function-declaration]
     if (uri.port && uri.port == ap_proxy_port_of_scheme(uri.scheme)) {
     ^**
/usr/lib64/apr-1/build/libtool --silent --mode=link gcc -std=gnu99  -pthread           -o mod_proxy_cluster.la -rpath /opt/apache2/modules -module -avoid-version mod_proxy_cluster.lo
/opt/apache2/build/instdso.sh SH_LIBTOOL='/usr/lib64/apr-1/build/libtool --silent' mod_proxy_cluster.la `pwd`
/usr/lib64/apr-1/build/libtool --silent --mode=install install mod_proxy_cluster.la /home/mod_cluster-1.3.10.Final/native/mod_proxy_cluster/
libtool: install: warning: remember to run `libtool --finish /opt/apache2/modules'

Apache httpd version
[root@localhost bin]# ./httpd -v
Server version: Apache/2.4.6 (Unix)
Server built:   Apr 25 2020 21:44:42

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

mod_cluster-1.3.10.Final.zip

After integration mod cluster modules (mod_advertise.so, mod_cluster_slotmem.so, mod_manager.so and mod_proxy_cluster.so) with Apache httpd, the mod_proxy_cluster.so module failed to load and getting below error from Apache httpd.
[root@localhost bin]# ./apachectl start
httpd: Syntax error on line 152 of /opt/apache2/conf/httpd.conf: Cannot load modules/mod_proxy_cluster.so into server: /opt/apache2/modules/mod_proxy_cluster.so: undefined symbol: proxy_module

Can you help provide the work around to fix the warning

**Comment by jfclere** [comment]
2.4.6 is not supported neither 1.3.10.
