### ISSUE TITLE
Error 526 - Invalid SSL certificate on https://modcluster.io/

### ISSUE THREAD

**Issue by superbob** [modcluster/mod_cluster#469]
Hi,

Since a couple of days, I see this error when trying to access the https://modcluster.io/ website :

![image](https://user-images.githubusercontent.com/1587431/88307320-15f68300-cd0c-11ea-8412-987c13928ae0.png)

Is there another way to see modcluster documentation ?

Florian.

**Comment by rhusar** [comment]
Thanks for the notice. No idea whats going on, since this is all managed by github pages and not us.

**Comment by rhusar** [comment]
Looks like bug with github pages, stuck at:

TLS certificate is being provisioned. This may take up to 15 minutes to complete.
1 of 3 
Certificate Request Error: Certificate provisioning will retry automatically in a short period, please be patient.

**Comment by rhusar** [comment]
Resolved couple weeks ago. Closing.

**Comment by abhay382** [comment]
Certificate Request Error: Certificate provisioning will retry automatically in a short period, please be patient.

**Comment by rhusar** [comment]
@abhay382 This works fine - try again - https://modcluster.io/ - perhaps you accidentally used a subdomain (like www or something)? Though, perhaps we should see about getting this to work with www subdomain since this habit seems to be still around.

**Comment by JackWong0303** [comment]
Hi, I encountered this problem today. Is there any way to download mod_cluster? Thanks

**Comment by dorianmariefr** [comment]
I had the same issue, switching from "SSL Strict" to "SSL Full" in Cloudflare fixed it
