### ISSUE TITLE
Prometheus metrics for mod_cluster_manager

### ISSUE THREAD

**Issue by daveram** [modcluster/mod_cluster#527]
Has there been any thought about having mod_cluster expose prometheus metrics for scraping context status over time instead of relying on soley on mod_cluster_manager?  Gets a bit much to parse through when we have many apps over many nodes, currently for many projects I see over 100 contexts total

**Comment by rhusar** [comment]
@daveram I believe this should be already possible in the Undertow implementation as that implementation exposes runtime resources, although, I have not tested this. However, I am going to assume you are using the native version, i.e. the Apache httpd modules?

**Comment by daveram** [comment]
Correct, we're running the mod_cluster httpd modules.  We're considering writing our own exporter to parse the results of mod_cluster_manager, but if there's a better way I'm all ears

**Comment by rhusar** [comment]
I am afraid there isn't a "better way" at the moment for the native modules. Nevertheless, this sound like a useful feature to be added for the native implementation as well.

**Comment by daveram** [comment]
Closing the loop on this one

We ended up writing a custom prometheus exporter that scrapes the contents of the mod_cluster_manager page into Prometheus metrics including node and context mappings
