### ISSUE TITLE
TLS certificate is being provisioned. This may take up to 15 minutes to complete.

### ISSUE THREAD

**Issue by PillPharmacy** [modcluster/mod_cluster#558]
![Screenshot 2022-01-17 5 56 49 PM](https://user-images.githubusercontent.com/97907151/149845580-05f82df8-be32-4636-ab49-495a7ddc98ae.png)

Ive had it saying TLS certificate is being provisioned for the past hour or so. I deleted and reset it and no use. Is this an error, can the mods do anything from their end or anything i should do from my end.

**Comment by rhusar** [comment]
I don't see how this is related to mod_cluster.
