### ISSUE TITLE
try download, compile and use mod_cluster-1.3.20.Final but not work

### ISSUE THREAD

**Issue by ericossj** [modcluster/mod_cluster#790]
trying these commands::

\# wget https://github.com/modcluster/mod_cluster/archive/refs/tags/1.3.20.Final.tar.gz
\# tar -xf 1.3.20.Final.tar.gz
\# cd mod_cluster-1.3.20.Final/native/
\# mkdir build
\# cd build/
\# cmake ../ -G "Unix Makefiles"
\# make
\# cp modules/*.so /etc/httpd/modules/
\# systemctl start httpd
\# systemctl start wildfly

but in apache console i see:
[mpm_prefork:notice] [pid 20745] AH00163: Apache/2.4.58 () OpenSSL/1.0.2k-fips mod_cluster/1.3.20.Final configured -- resuming normal operations

then
AH01144: No protocol handler was valid for the URL /rest/api/v1/autenticate
AH01144: No protocol handler was valid for the URL /app.css
AH01144: No protocol handler was valid for the URL /app.js
AH01144: No protocol handler was valid for the URL /..........................

only version that works is:
[mpm_prefork:notice] [pid 26068] AH00163: Apache/2.4.58 () OpenSSL/1.0.2k-fips mod_cluster/1.3.11.Final configured -- resuming normal operations

what am I doing wrong ?

**Comment by jajik** [comment]
Hi, could you please add a conf file you're using with the modules loaded and a bigger chunk of logs? If you're using httpd from your distribution's repository, what distro are you using?

**Comment by ericossj** [comment]
#-------------------------------------------------------------------------------------------------------------
Timeout 600
ProxyTimeout 600
ServerSignature Off
ServerTokens Prod
LimitRequestLine 81920
LimitRequestFieldSize 81920
#-------------------------------------------------------------------------------------------------------------
<IfModule mpm_prefork_module>
    StartServers 20
    MinSpareServers 5
    MaxSpareServers 20
    ServerLimit 512
    MaxRequestWorkers 512
    MaxConnectionsPerChild 2048
</IfModule>
#-------------------------------------------------------------------------------------------------------------
<VirtualHost *:80>
    ServerName www.site.com.br
    ServerAlias site.com.br
    DocumentRoot /var/www/www.site.com.br
    <Directory /var/www/www.site.com.br>
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.php$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.php [L]
        </IfModule>
    </Directory>
    Redirect / https://www.site.com.br
</VirtualHost>
#-------------------------------------------------------------------------------------------------------------
LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so
LoadModule manager_module modules/mod_manager.so
LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule advertise_module modules/mod_advertise.so
#-------------------------------------------------------------------------------------------------------------
<IfModule manager_module>
    LogLevel warn
    Listen 4444
    CreateBalancers 1
    ManagerBalancerName mycluster
    UseAlias Off
    Maxcontext 200
    Maxnode 200
    Maxhost 200
    PersistSlots Off
    AllowDisplay On
    <VirtualHost *:4444>
        KeepAliveTimeout 4
        MaxKeepAliveRequests 300
        ServerAdvertise Off
        EnableMCPMReceive
        # where your worker nodes connect from
        <Location />
            Require ip 127.0.0
            # Require all granted
        </Location>
        # where administrator reads the console from
        <Location /mcm>
            SetHandler mod_cluster-manager
            AuthType Basic
            AuthName "mod_cluster"
            AuthUserFile /etc/modclusterpassword
            Require user mcm
        </Location>
    </VirtualHost>
</IfModule>
#-------------------------------------------------------------------------------------------------------------
FileETag None
#-------------------------------------------------------------------------------------------------------------
<IfModule mod_deflate.c>
    SetOutputFilter DEFLATE
    # don't compress
    SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png|pdf)$ no-gzip dont-vary
    SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|bz2|sit|rar)$ no-gzip dont-vary
    # dealing with proxy servers
    <IfModule mod_headers.c>
        Header append Vary User-Agent
    </IfModule>
</IfModule>
#-------------------------------------------------------------------------------------------------------------
# 60*60*24*30 = 2592000 = 1 mes
# 60*60*24*60 = 5184000 = 2 meses
<IfModule mod_headers.c>
    Header unset ETag
    # Header set Cache-Control public,max-age=0,no-cache,no-store,must-revalidate
    Header unset Cache-Control
    <FilesMatch "\.(html|pdf|jpg|jpeg|png|gif|ico|css|js|ttf|ttc|otf|eot|woff|woff2|font.css)$">
        Header set Cache-Control public,max-age=2592000
	Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
    <LocationMatch "\.(jpg|jpeg|png|gif|ico|css|js|ttf|ttc|otf|eot|woff|woff2|font.css)$">
        Header set Cache-Control public,max-age=2592000
    </LocationMatch>
</IfModule>
#-------------------------------------------------------------------------------------------------------------
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresDefault A0
    <FilesMatch "\.(jpg|jpeg|png|gif|ico|css|js|ttf|ttc|otf|eot|woff|woff2|font.css)$">
        ExpiresDefault A2592000
    </FilesMatch>
    <LocationMatch "\.(jpg|jpeg|png|gif|ico|css|js|ttf|ttc|otf|eot|woff|woff2|font.css)$">
        ExpiresDefault A2592000
    </LocationMatch>
</IfModule>
#-------------------------------------------------------------------------------------------------------------
<VirtualHost *:80>
    ServerName client.site.com.br
    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
    </IfModule>
</VirtualHost>
<VirtualHost *:443>
    ServerName client.site.com.br
    ProxyPass / balancer://mycluster stickysession=JSESSIONID|jsessionid nofailover=On
    ProxyPassReverse / balancer://mycluster
    ProxyPreserveHost On
    KeepAliveTimeout 4
    MaxKeepAliveRequests 300
    SSLEngine on
    SSLProtocol all -SSLv2 -SSLv3
    SSLCipherSuite ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    SSLHonorCipherOrder on
    #SSLOptions +StrictRequire
    SSLCertificateFile /etc/letsencrypt/live/site.com.br/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/site.com.br/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/site.com.br/chain.pem
</VirtualHost>

**Comment by ericossj** [comment]
[mod_cluster.txt](https://github.com/modcluster/mod_cluster/files/14899597/mod_cluster.txt)

**Comment by jfclere** [comment]
ProxyPass / balancer://mycluster stickysession=JSESSIONID|jsessionid nofailover=On
    ProxyPassReverse / balancer://mycluster
Could you try:
    ProxyPass / balancer://mycluster/ stickysession=JSESSIONID|jsessionid nofailover=On
    ProxyPassReverse / balancer://mycluster/

**Comment by ericossj** [comment]
I followed your instructions and it worked,
Thank you so much guys,
you guys are awesome!

**Comment by rhusar** [comment]
Excellent! Closing as resolved.

Just BTW we also have discussion spaces open for questions: https://github.com/modcluster/mod_cluster/discussions
